// Generated by `pnpm brand` from src/config/brand.ts and src/config/brand-mark.ts.
// Do not edit: change those files and run the command again.
//
// The edge functions are bundled from supabase/functions alone and cannot
// import from src/, so the name and the mark reach them through this copy.
// tests/unit/brand.test.ts fails when it falls behind.

export const BRAND_NAME = "Coridor";

/** Lowercase ASCII letters and digits: a file name, a crawler's name. */
export const BRAND_SLUG = "coridor";

export const MARK = {
  grid: 24,
  ramp: "M3 18 H6.5 L13 6 H21",
  deck: "M11 18 H21",
} as const;
