// Generated by `pnpm brand` from src/config/brand.ts, brand-mark.ts and company.ts.
// Do not edit: change those files and run the command again.
//
// The edge functions are bundled from supabase/functions alone and cannot
// import from src/, so the name, the mark and the operator's identification
// reach them through this copy.
// tests/unit/brand.test.ts fails when it falls behind.

export const BRAND_NAME = "Transauto Bursa";

/** Lowercase ASCII letters and digits: a file name, a crawler's name. */
export const BRAND_SLUG = "transautobursa";

/** Who operates the platform, one line, for the bottom of every e-mail. */
export const OPERATOR_LINE = "MRO WEMAX SRL · CUI RO 41150110 · J16/1561/2019 · EUID ROONRC.J16/1561/2019 · Str. Brăila 230, Craiova, jud. Dolj, cod poștal 200641, România";

export const MARK = {
  grid: 24,
  car: "M3.5 13.5 V10 Q3.5 8 5.5 8 H7.5 L10.5 4 H16 L19 8 H19.5 Q21.5 8 21.5 10 V13.5 Z",
  deck: "M2 20 L5 17 H22",
} as const;
