// Generated by `pnpm brand` from src/config/brand.ts and src/config/brand-mark.ts.
// Do not edit: change those files and run the command again.
//
// The edge functions are bundled from supabase/functions alone and cannot
// import from src/, so the name and the mark reach them through this copy.
// tests/unit/brand.test.ts fails when it falls behind.

export const BRAND_NAME = "Transauto Bursa";

/** Lowercase ASCII letters and digits: a file name, a crawler's name. */
export const BRAND_SLUG = "transautobursa";

export const MARK = {
  grid: 24,
  car: "M3.5 13.5 V10 Q3.5 8 5.5 8 H7.5 L10.5 4 H16 L19 8 H19.5 Q21.5 8 21.5 10 V13.5 Z",
  deck: "M2 20 L5 17 H22",
} as const;
