/** Romanian copy for the departures board and the carrier's own routes. */
export const departuresCopy = {
  board: {
    eyebrow: 'Trasee disponibile',
    title: 'Trasee',
    titleSoft: 'cu locuri libere.',
    lede: 'Platforme care circulă oricum pe ruta lor. Plătești locul, nu camionul.',
    tabs: {
      toate: 'Toate',
      tur: 'Pe tur',
      retur: 'Pe retur',
    },
    count: (n: number) => (n === 1 ? 'Un traseu' : `${n} trasee`),
    sortNote: 'Ordonate după data cea mai apropiată.',
    signedOutNote:
      'Vezi traseul și locurile libere. Firma care transportă apare după autentificare.',
  },

  filters: {
    title: 'Filtre',
    fromCountry: 'Țara de plecare',
    fromCounty: 'Județ / regiune plecare',
    toCountry: 'Țara de sosire',
    toCounty: 'Județ / regiune sosire',
    dateFrom: 'De la data',
    dateTo: 'Până la data',
    minSeats: 'Locuri libere, minimum',
    vehicleType: 'Tipul vehiculului',
    scope: 'Acoperire',
    scopeDomestic: 'Intern',
    scopeInternational: 'Internațional',
    any: 'Oricare',
    apply: 'Caută',
    clear: 'Șterge filtrele',
  },

  card: {
    seatsUnknown: 'Locuri la cerere',
    noPrice: 'Preț la cerere',
    open: 'Vezi traseul',
    full: 'Platformă plină',
  },

  empty: {
    title: 'Încă nu sunt trasee publicate pentru această căutare.',
    body: 'Bursa este la început. Publică o cerere și transportatorii o văd, sau lasă-ne adresa și te anunțăm când apare un traseu potrivit.',
    request: 'Publică o cerere',
    alert: 'Anunță-mă când apare un traseu',
    alertSignedOut: 'Intră în cont ca să primești anunțul',
    alertSaved: 'Gata. Te anunțăm pe e-mail când apare un traseu care se potrivește.',
    alertExists: 'Ai deja o alertă salvată pentru această căutare.',
    carrierAlert:
      'Ești transportator? Salvează-ți căutarea pe panoul de cereri și te anunțăm când apare o cerere pe ruta asta.',
    carrierAlertAction: 'Salvează căutarea de cereri',
    clear: 'Vezi toate traseele',
  },

  detail: {
    back: 'Înapoi la trasee',
    route: 'Traseul',
    seats: 'Locuri pe platformă',
    services: 'Tipul serviciului',
    accepts: 'Ce urcă pe platformă',
    window: 'Perioada',
    price: 'Preț orientativ',
    carrier: 'Transportator',
    carrierHidden: 'Intră în cont ca să vezi firma care transportă.',
    verified: 'Firmă verificată',
    request: 'Cere transport pe acest traseu',
    contact: 'Contactează transportatorul',
    seePlans: 'Vezi planurile și limitele',
    full: 'Platforma este plină. Poți publica o cerere și transportatorul te anunță dacă se eliberează un loc.',
    departed: 'Traseul a plecat deja.',
    similar: 'Trasee asemănătoare',
    noSimilar: 'Nu avem deocamdată alt traseu pe această rută.',
    notFound: 'Traseul nu mai este disponibil.',
  },

  mine: {
    eyebrow: 'Traseele mele',
    title: 'Traseele firmei',
    lede: 'Traseele publicate, locurile ocupate și rezervările care așteptă un răspuns.',
    empty: 'Niciun traseu publicat încă.',
    add: 'Publică un traseu',
    edit: 'Modifică',
    stop: 'Retrage de pe bursă',
    duplicate: 'Dublează ca retur',
    stopped: 'Traseul a fost retras de pe bursă.',
    duplicated: 'Am pregătit returul ca ciornă. Verifică datele și publică-l.',
    pending: 'Rezervări în așteptare',
    noPending: 'Nicio rezervare în așteptare.',
    confirm: 'Confirmă',
    reject: 'Refuză',
    confirmed: 'Rezervarea a fost confirmată și comanda creată.',
    rejected: 'Rezervarea a fost refuzată.',
    seatsTaken: (taken: number, total: number) => `${taken} din ${total} locuri ocupate`,
  },

  form: {
    eyebrow: 'Traseu nou',
    title: 'Publică un traseu',
    lede: 'Traseul apare pe bursă cu orașele și locurile libere. Datele firmei rămân ascunse până când cineva îți scrie.',
    direction: 'Direcția',
    directionTur: 'Pe tur — merg încolo',
    directionRetur: 'Pe retur — mă întorc',
    from: 'De unde pleci',
    to: 'Unde ajungi',
    waypoints: 'Orașe pe drum',
    waypointsHint: 'Separate prin virgulă. Ajută la potrivirea cu cererile.',
    availableFrom: 'Disponibil de la',
    availableTo: 'Până la',
    vehicle: 'Vehiculul',
    noVehicle:
      'Nu ai niciun vehicul cu documentele în regulă. Un traseu poate fi publicat doar cu ITP, RCA și copia conformă valabile.',
    noVehicleAction: 'Mergi la flotă',
    slots: 'Locuri pe platformă',
    slotsHint: 'Câte vehicule încap. Lasă gol dacă nu transporți pe platformă.',
    accepted: 'Ce accepți pe platformă',
    services: 'Tipul serviciului',
    maxDetour: 'Ocol maxim acceptat (km)',
    price: 'Preț orientativ pe loc',
    priceHint: 'Opțional. Apare pe bursă marcat „orientativ”.',
    submit: 'Publică traseul',
    saveDraft: 'Salvează ca ciornă',
    published: 'Traseul este pe bursă.',
  },
} as const;
