#!/usr/bin/env bash
# Rebuilds supabase/functions/contract-pdf/fonts.ts: Inter Regular and
# SemiBold, subset to what a Romanian contract needs, as base64.
#
#   bash scripts/contract-fonts.sh <dir with Inter-Regular.ttf and Inter-SemiBold.ttf>
#
# Source: Inter 4.001 static TTFs (the ones in @expo-google-fonts/inter@0.4.2,
# or the release zip at https://github.com/rsms/inter). SIL Open Font
# License 1.1, no Reserved Font Name, so a subset may keep the name. The
# licence travels next to the output in fonts/OFL.txt and inside each font's
# name table (IDs 0, 13, 14 are kept).
#
# Why embedded as base64 rather than read from disk: the function is
# deployed with `supabase functions deploy --use-api`, which bundles the
# import graph. A module is in the graph; a .ttf next to it is not.
#
# Why subset: the full fonts are 340 KB each, and the renderer only ever
# draws Latin, Latin-1, Latin Extended-A, ș ț Ș Ț (U+0218–U+021B, the
# comma-below forms Romanian uses) and typographic punctuation („ ” – — … €).
#
# Needs: pyftsubset (pip install fonttools), node.
set -euo pipefail

src="${1:?usage: contract-fonts.sh <dir with Inter-Regular.ttf and Inter-SemiBold.ttf>}"
root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/supabase/functions/contract-pdf/fonts.ts"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

unicodes="U+0020-007E,U+00A0-00FF,U+0100-017F,U+0218-021B,U+2010-2027,U+2030,U+2039-203A,U+20AC,U+2116,U+2122,U+2192,U+2212"

for weight in Regular SemiBold; do
  pyftsubset "$src/Inter-$weight.ttf" \
    --unicodes="$unicodes" \
    --layout-features='kern,liga,calt,tnum,lnum' \
    --name-IDs='*' --name-languages='*' \
    --no-hinting \
    --output-file="$work/Inter-$weight.ttf"
done

node - "$work" "$out" <<'JS'
const { readFileSync, writeFileSync } = require('node:fs');
const [work, out] = process.argv.slice(2);
const b64 = (weight) => readFileSync(`${work}/Inter-${weight}.ttf`).toString('base64');
const wrap = (s) => `[\n${s.match(/.{1,100}/g).map((line) => `  '${line}',`).join('\n')}\n].join('')`;
writeFileSync(
  out,
  `// Generated by scripts/contract-fonts.sh. Do not edit by hand.
//
// Inter 4.001, Copyright 2016-2020 The Inter Project Authors
// (https://github.com/rsms/inter), SIL Open Font License 1.1 — see
// fonts/OFL.txt. Subset to Latin, Latin-1, Latin Extended-A, ș ț Ș Ț and
// typographic punctuation.

/** Inter Regular, TrueType, base64. */
export const INTER_REGULAR = ${wrap(b64('Regular'))};

/** Inter SemiBold, TrueType, base64. */
export const INTER_SEMIBOLD = ${wrap(b64('SemiBold'))};
`,
);
JS

echo "Wrote ${out#"$root"/}"
