#!/usr/bin/env bash
# Regenerates src/lib/supabase/database.types.ts from the migrations in this
# repository, on a throwaway local database.
#
#   pnpm gen:types
#
# Why not `supabase gen types`: that command starts a container to run
# postgres-meta, so it needs Docker. This drives the same generator
# (@supabase/postgres-meta, the package the CLI bundles) directly against a
# database built from supabase/migrations, so the types always describe the
# schema in this branch rather than whatever is currently deployed.
#
# Needs a local Postgres (15+) with contrib, and createdb / psql / dropdb on
# PATH. Connection settings come from the usual PG* environment variables.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
db="coridor_types_$(date +%s)_$$"
work="$(mktemp -d)"
out="$root/src/lib/supabase/database.types.ts"

cleanup() {
  dropdb --if-exists "$db" >/dev/null 2>&1 || true
  rm -rf "$work"
}
trap cleanup EXIT

psql_run() { psql -X -q -v ON_ERROR_STOP=1 -d "$db" "$@"; }

createdb "$db"

# Mirror the hosted project's extension layout before the migrations run.
# Supabase preinstalls pgcrypto in `extensions`, so `create extension if not
# exists "pgcrypto"` is a no-op there and its functions never reach the
# public API. pg_trgm really is in `public` on the hosted project (an
# accepted advisor finding), so it is left alone. Without this the generated
# file carries ~15 pgcrypto functions that the deployed schema does not
# expose.
psql_run -c 'create schema if not exists extensions' >/dev/null
psql_run -c 'create extension if not exists "pgcrypto" schema extensions' >/dev/null

psql_run -f "$root/supabase/tests/supabase_shim.sql" >/dev/null

for f in "$root"/supabase/migrations/*.sql; do
  if ! err="$(psql_run -f "$f" 2>&1)"; then
    echo "Migration failed: $(basename "$f")" >&2
    echo "$err" | grep -E "ERROR|DETAIL|HINT" >&2 || echo "$err" >&2
    exit 1
  fi
done

cat > "$work/package.json" <<'JSON'
{ "name": "coridor-gen-types", "private": true, "type": "module" }
JSON

npm i --prefix "$work" --no-audit --no-fund --silent @supabase/postgres-meta@0.91.6 >/dev/null 2>&1

cat > "$work/gen.mjs" <<'JS'
import { PostgresMeta } from '@supabase/postgres-meta/dist/lib/index.js';
import { getGeneratorMetadata } from '@supabase/postgres-meta/dist/lib/generators.js';
import { apply } from '@supabase/postgres-meta/dist/server/templates/typescript.js';

const pgMeta = new PostgresMeta({ connectionString: process.argv[2], max: 1 });
const { data, error } = await getGeneratorMetadata(pgMeta, {
  includedSchemas: ['public'],
  excludedSchemas: [],
});
if (error) {
  console.error(`postgres-meta: ${error.message}`);
  process.exit(1);
}
process.stdout.write(await apply({ ...data, detectOneToOneRelationships: true }));
await pgMeta.end();
JS

host="${PGHOST:-localhost}"
port="${PGPORT:-5432}"
user="${PGUSER:-postgres}"
url="postgresql://${user}:${PGPASSWORD:-postgres}@${host}:${port}/${db}"

{
  cat <<'HEADER'
// Generated by `pnpm gen:types` from supabase/migrations. Do not edit by
// hand: the next regeneration overwrites it. If a type here is wrong, the
// migration is wrong.
HEADER
  NODE_PATH="$work/node_modules" node "$work/gen.mjs" "$url"
} > "$work/database.types.ts"

mv "$work/database.types.ts" "$out"
echo "Wrote ${out#"$root"/} from ${db}"
